// error-types.enum.ts
export enum ErrorType {
  DATABASE_ERROR = 'DATABASE_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  RESERVATION_CREATION_ERROR = 'RESERVATION_CREATION_ERROR',
  USER_VALIDATION_ERROR = 'USER_VALIDATION_ERROR',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  // ... other error types
}
