#!/bin/bash

commitRegex="^(feat|draft|patch|hotfix): NEST-[0-9]{2,10} .+"
errorMessage="Commit message does not follow the required format (e.g., 'feat: MYP-3495 Added new feature')"

if ! grep -qE "$commitRegex" "$1"; then
    echo "$errorMessage" >&2
    exit 1
fi

