#!/bin/bash

export PATH="/home/christiandominguez/.cargo/bin:/home/christiandominguez/.deno/bin:/usr/local/go/bin:/home/christiandominguez/.nvm/versions/node/v18.16.0/bin:/usr/local/sbin:/usr/local/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/sbin:/usr/bin:/sbin:/bin:/opt:/usr/games:/usr/local/games:/snap/bin:/home/christiandominguez/.local/bin:/home/christiandominguez/go/bin:$PATH"

# Rest of your script...

commitRegex="^(feat|draft|patch|hotfix): NEST-[0-9]{2,10} .+"
errorMessage="Commit message does not follow the required format (e.g., 'feat: MYP-3495 Added new feature')"

if ! grep -qE "$commitRegex" "$1"; then
    echo "$errorMessage" >&2
    exit 1
fi

