#!/bin/bash

branchPattern="^MYP-[0-9]{2,10}$"
branchName=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,' | tr -d '[:space:]')

echo "Extracted branch name: '$branchName'"

if ! echo "$branchName" | grep -qE "$branchPattern"; then
    echo "Error: Branch name '$branchName' does not match the pattern 'MYP-<number>'."
    exit 1
fi

exit 0
